GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5fb721d7985aec250ce4c9c4

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Another",
  "subscribedChannel": "Random"
}

###

DELETE http://localhost:3000/subscribers/5fb71f6a4692d35b38ca8994

###

PATCH http://localhost:3000/subscribers/5fb721d7985aec250ce4c9c4
Content-Type: application/json

{
  "subscribedChannel": "favChannel"
}